name: Python UnitTest

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-16.04, ubuntu-18.04, macos-10.14, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Check environment and install dependences 
      run: |
          echo "\$PATH: " $PATH
          python --version
          python3 --version
          pip3 --version

          if [[ "$OSTYPE" == "linux-gnu" ]]; then
              echo "OS: Linux"
              # nmap is needed for the man parser in UnitTest
              sudo apt-get install nmap
          elif [[ "$OSTYPE" == "darwin"* ]]; then
              echo "OS: Mac OSX"
          else
              echo "unknown: " $OSTYPE
          fi

    - name: Test with UnitTest
      run: |
          python3 -m unittest discover -s /home/runner/work/fastHistory/fastHistory/
