name: Python UnitTest

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-18.04, macos-10.15]
            python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check environment and install dependences 
      run: |
          python3 --version
          pip3 --version

          if [[ "$OSTYPE" == "linux-gnu" ]]; then
              echo "OS: Linux"
              pip3 install bashlex
              pip3 install pyperclip
              sudo apt-get install nmap # nmap is needed for the man parser in UnitTest
          elif [[ "$OSTYPE" == "darwin"* ]]; then
              echo "OS: Mac OSX"
              pip3 install bashlex
              pip3 install pyperclip
              brew install nmap
          else
              echo "unknown: " $OSTYPE
              exit 1
          fi
    - name: Test with UnitTest
      run: |
        if [[ "$OSTYPE" == "linux-gnu" ]]; then
          echo "OS: Linux"
          python3 -m unittest discover -s /home/runner/work/fastHistory/fastHistory/
        elif [[ "$OSTYPE" == "darwin"* ]]; then
          echo "OS: Mac OSX"
          python3 -m unittest discover -s /Users/runner/runners/*/work/fastHistory/fastHistory
        else
          echo "unknown: " $OSTYPE
          exit 1
        fi
    - name: Read UnitTest output logs
      if: always()
      run: |
        if [[ "$OSTYPE" == "linux-gnu" ]]; then
          echo "OS: Linux"
          for i in /home/runner/work/fastHistory/fastHistory/data_test/*.txt; do printf "\n\n## $i ## \n\n" ; cat "$i"; printf "\n" ; done ;
        elif [[ "$OSTYPE" == "darwin"* ]]; then
          echo "OS: Mac OSX"
          for i in /Users/runner/runners/*/work/fastHistory/fastHistory/data_test/*.txt; do printf "\n\n## $i ## \n\n" ; cat "$i"; printf "\n" ; done ;
        else
          echo "unknown: " $OSTYPE
          exit 1
        fi
